### PR TITLE
Add missing constants and data types for Linux timestamping API

### PR DESCRIPTION
**Pull request by jsitnicki**
Add constants for SOF_* flags defined in linux/net_tstamp.h kernel header as of Linux v4.13.

These are needed to make use of SO_TIMESTAMPING socket option under Linux.

### CODE REVIEW

**Comment by justincormack** [comment]
The CI is complaining as the tests for whether symbols have correct values vs C headers cant find the symbols. It is fine to add them to the list that are ignored in these tests...

**Comment by jsitnicki** [comment]
Sorry about this oversight. I will fix it.

**Comment by jsitnicki** [comment]
Hi @justincormack, tests are all patched up now. Also, I have extended changes and added a missing data type that is also a part of Linux timestamping API. With these changes it is possible to use the timestamping API ([example](https://github.com/jsitnicki/rushit/blob/master/examples/tcp-ack-interval.lua)). I've renamed the PR subject to better reflect the scope. Please take a look.

**Comment by justincormack** [comment]
Thanks!

**Pull request merged**
